baseURL = "https://valvali.net/"
languageCode = "fr-fr"
title = "Vali"
theme = "hello-friend-ng"
pagerSize     = 10

[params]
  AuthorName = 'Vali'
  dateform        = "Jan 17, 2021"
  dateformShort   = "Jan 2"
  dateformNum     = "2021-17-01"
  dateformNumTime = "2021-17-01 19:51"

  # Subtitle for home
  Subtitle = "Un gars sur Internet."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Chez Vali"
  keywords = "vali, meme"
  images = [""]

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/Valvalidu57"

  [[params.social]]
    name = "email"
    url  = "mailto:superval57@hotmail.fr"

  [[params.social]]
    name = "twitch"
    url  = "https://twitch.tv/valvali"

  [[params.social]]
    name = "bluesky"
    url  = "https://bsky.app/profile/valvali.net"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Vali"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Vali"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "T ki ?"
    url        = "/about/about"
 [[menu.main]]
    identifier = "posts"
    name       = "Trucs"
    url        = "/posts"
