baseURL = "https://valvali.net/"
languageCode = "fr_FR"
defaultContentLanguage = 'fr'
title = "Vali"
theme = "LoveIt"
pagerSize     = 10
enableGitInfo = true

[params]
  AuthorName = 'Vali'
  DateForm = "2.1.2006"
  dateFormat = "02-01-2006"

  # Subtitle for home
  Subtitle = "Un gars sur Internet."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Chez Vali"
  keywords = "vali, meme"
  images = [""]

  [params.social]
    twitter = "Valvalidu57"
    email = "superval57@hotmail.fr"
    twitch = "valvali"
    bluesky = "valvali.net"
    steam = "valvalidu57"

  # LoveIt theme settings
  [params.author]
    name = "Vali"
    link = "/about/about"
    avatarURL = "/img/valiavatars.gif"

  [params.header.title]
    name = "Vali"
    pre = ""
    post = ""

  [params.home.profile]
    enable = true
    title = "Vali"
    subtitle = "Un gars sur Internet."
    avatarURL = "/img/valiavatars.gif"

  [params.page]
    toc.enable = true
    math.enable = false
    code.copy = true

  [params.page.share]
    enable = true

  [params.footer]
    enable = true
    author = true
    hugo = true
    copyright = true
    since = 2023

  [params.search]
    enable = true
    type = "lunr"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[security]
  enableInlineShortcodes = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.fr]
    title = "Vali"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.fr.params.logo]
      logoText = "Vali"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "T ki ?"
    url        = "/about/about"
 [[menu.main]]
    identifier = "posts"
    name       = "Trucs"
    url        = "/posts"
 [[menu.main]]
    identifier = "freegames"
    name       = "Jeux Gratuits"
    url        = "/posts/freegames"
